<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Payment\Block\Transparent\Iframe $block */
$params = $block->getParams();
?>
<html>
    <head>
        <script>
        <?php if (isset($params['redirect'])): ?>
            window.location="<?= $block->escapeUrl($params['redirect']) ?>";
        <?php elseif (isset($params['redirect_parent'])): ?>
            var require = window.top.require;
            require(
                [
                    'jquery'
                ],
                function($) {
                    var parent = window.top;
                    $(parent).trigger('clearTimeout');
                    parent.location="<?= $block->escapeUrl($params['redirect_parent']) ?>";
                }
            );
        <?php elseif (isset($params['error_msg'])): ?>
            var require = window.top.require;
            require(
                [
                    'jquery',
                    'Magento_Ui/js/model/messageList',
                    'mage/translate',
                    'Magento_Checkout/js/model/full-screen-loader'
                ],
                function($, globalMessageList, $t, fullScreenLoader) {
                    var parent = window.top;
                    $(parent).trigger('clearTimeout');
                    fullScreenLoader.stopLoader();
                    globalMessageList.addErrorMessage({
                        message: $t('An error occurred on the server. Please try to place the order again.')
                    });
                }
            );
        <?php elseif (isset($params['order_success'])): ?>
            window.top.location = "<?= $block->escapeUrl($params['order_success']) ?>";
        <?php else: ?>
            var require = window.top.require;
            <?php if(isset($params['avoid_treedsecure_check'])):
                ?>
                var treedsecure_redirect = false;
                <?php
            else:
                ?>
                var treedsecure_redirect = true;
            <?php
            endif;
            ?>
            require(
                [
                    'jquery',
                    'Magento_Checkout/js/model/quote',
                    'Magento_Checkout/js/action/place-order',
                    'Magento_Checkout/js/action/redirect-on-success',
                    'Magento_Ui/js/model/messageList',
                    'mage/translate',
                    'Magento_Checkout/js/model/full-screen-loader'
                ],
                function($, quote, placeOrderAction, redirectOnSuccessAction, globalMessageList, $t, fullScreenLoader) {
                    var parent = window.top;
                    var payfortconfig = parent.checkoutConfig.payment.md_payfort;
                    var threedsecure = payfortconfig.threedacitve;
                    if(threedsecure && treedsecure_redirect)
                    {
                         var threedcheckUrl = '<?php echo $block->getUrl('payfort/MerchantPage/ThreedRequest'); ?>';
                        $(parent).trigger('clearTimeout');
                        $.ajax(''+threedcheckUrl+'?isAjax=true',{
                            method: 'POST',
                            dataType: 'html',
                            showLoader: true,
                            complete: function(responseresult){
                                var result = $.parseJSON(responseresult.responseText);
                                if(result.success == true) {
                                    var response = result.md_payfort;
                                    console.log(response);
                                    var threedurl = response['3ds_url'];
                                    var parent = window.top;
                                    $(parent).trigger('clearTimeout');
                                    parent.location = threedurl;
                                }
                                else {
                                    var parent = window.top;
                                    $(parent).trigger('clearTimeout');
                                    fullScreenLoader.stopLoader();
                                    globalMessageList.addErrorMessage({
                                        message: $t('An error occurred on the server. Please try to place the order again.')
                                    });
                                }
                            }
                        });
                    }
                    else {
                         $(parent).trigger('clearTimeout');
                         $.when(
                            placeOrderAction({'method': quote.paymentMethod().method})
                        ).done(
                            function () {
                                redirectOnSuccessAction.execute();
                            }
                        );
                    }
                }
            );
        <?php endif; ?>
        </script>
    </head>
    <body></body>
</html>
